[initialisation]
field_to_keep = "Adj Close"
begin_date = "2008-01-01"
end_date = "2009-12-31"

[portfolio]
Citibank = 0.25
Morgan_Stanley = 0.25
Goldman_Sachs = 0.25
J_P_Morgan = 0.25

[view_mode]
print = true
chart = true

[view]
closing = "Prix de clôture"
returns = "Rendements du portefeuille"
volatility = "Volatilité annualisée"
covariance = "Matrice de covariance"

[chart]
color = "black"